baseurl: "" # the subpath of your site, e.g. /blog
url: "https://premiersimgl.com" # the base hostname & protocol for your site, e.g. http://example.com
title: PremierSimGL
description: The biggest Formula 1 racing gaming league on PlayStation & PC
twitter:
  username: PremierSimGL
  card: summary
logo: /assets/site-img/PSGL-Logo-192.png
social:
  name: PremierSimGL
  links:
    - https://twitter.com/PremierSimGL
    - https://www.youtube.com/c/PremierSimGamingLeagues
    - https://discord.com/invite/s9TzzCb
webmaster_verifications:
  google: WT0ppqOYjPEyDeIiNjOhyvlOCBzs8BRCxBQBwgkBjmQ
excerpt_separator: <!--more-->
timezone: Europe/London

defaults:
  -
    scope:
      path:            "admin/"
    values:
      sitemap:         false

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-sitemap

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md

kramdown:
  parse_block_html: true

sass:
  style: compressed

target-blank:
  noreferrer: false

permalink: /:categories/:title

collections:
  custom_pages:
    output: true
  seasons:
    output: true
  leagues:
    output: true
  competitions:
  signups:
  settings:
