[build]
  command = "jekyll build"
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection =  "0"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy= "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=63072000;includeSubDomains;preload"

[[headers]]
  for = "/admin"
  [headers.values]
    X-Robots-Tag= "noindex"

[[redirects]]
  from = "https://mx.premiersimgl.com/*"
  to = "https://api.mixpanel.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/js/mx-2-latest.min.js"
  to = "https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js"
  status = 200
  force = true

[[redirects]]
  from = "/index.php"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "https://playstationgl.com/*"
  to = "https://www.premiersimgl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.playstationgl.com/*"
  to = "https://www.premiersimgl.com/:splat"
  status = 301
  force = true

[build.environment]
  TZ = "Europe/London"
  JEKYLL_ENV="production"
  JEKYLL_LOG_LEVEL="warn"

[functions]
  directory = "functions"
